authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name="login"),
    path("logout/", authapp.logout, name="logout"),

    path("register/", authapp.register, name="register"),
    path("edit/", authapp.edit, name="edit"),
    path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),

]

basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='index'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit')
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import index, contact


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', index, name='index'),
    path('contact/', contact, name='contact'),

    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('order/', include('ordersapp.urls', namespace='order')),

    path('', include('social_django.urls', namespace='social'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from .views import products, product


app_name = 'mainapp'

urlpatterns = [
    path('', products, name='products'),
    path('category/<int:pk>/', products, name='category'),
    path('category/<int:pk>/page/<int:page>/', products, name='page'),
    path('product/<int:pk>/', product, name='details'),

]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.CASCADE,
    )
    name = models.CharField(
        verbose_name='имя продукта',
        max_length=128,
    )
    image = models.ImageField(
        upload_to='products_images',
        blank=True,
    )
    short_desc = models.CharField(
        verbose_name='короткое описание',
        max_length=60,
        blank=True,
    )
    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )
    price = models.DecimalField(
        verbose_name='цена продукта',
        max_digits=8,
        decimal_places=2,
        default=0,
    )
    quantity = models.PositiveIntegerField(
        verbose_name='количество на складе',
        default=0,
    )

    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name} ({self.category.name})'

mainapp/views.py
import random

from django.shortcuts import render, get_object_or_404

from basketapp.models import Basket
from mainapp.models import ProductCategory, Product
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger



def get_hot_product():
    products = Product.objects.all()

    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)

    return same_products


def products(request, pk=None, page=1):
    title = 'каталог'
    links_menu = ProductCategory.objects.all()
    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)
    products = Product.objects.all().order_by('price')

    if pk is not None:
        if pk == 0:
            products = Product.objects.all().order_by('price')
            category = {'pk': 0, 'name': 'все'}
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk).order_by('price')

        paginator = Paginator(products, 1)

        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        context = {
            'title': title,
            'links_menu': links_menu,
            'products': products_paginator,
            'category': category,
            'hot_product': hot_product,
            'same_products': same_products,
        }
        return render(request, 'products.html', context=context)

    context = {
        'title': title,
        'links_menu': links_menu,
        'products': products,
        'hot_product': hot_product,
        'same_products': same_products,
    }
    return render(request, 'products.html', context=context)


def product(request, pk):
    title = 'продукты'

    context = {
        'title': title,
        'links_menu': ProductCategory.objects.all(),
        'product': get_object_or_404(Product, pk=pk),
    }

    return render(request, 'product_details.html', context)

mainapp/templates/product_details.html
{% extends 'base.html' %}
{% load static %}
{% block css%}
<link rel="stylesheet" type="text/css" href="{% static 'mainapp/style.css' %}">
{% endblock %}

{% block content %}
<div class="hero-white">
    <div class="header clearfix">
        {% include "includes/main_menu.html" %}
        <a href="#" class="basket"></a>
    </div>
</div>

<div class="details">
    <div class="details-products">
        <div class="details-slider">
            <div class="slider-product">
                <img src="{{product.image.url}}">
            </div>
            <div class="slider-control">
                <div class="block">
                    <a href="#"><img src="{% static '/geekshop/img/controll.jpg' %}" alt="">
                        <div class="text"></div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="{% static '/geekshop/img/controll1.jpg' %}" alt="">
                        <div class="text"></div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="{% static '/geekshop/img/controll2.jpg' %}" alt="">
                        <div class="text"></div>
                    </a>
                </div>
            </div>
        </div>

        <div class="description">
            <h3 class="big-bold">{{ product.short_desc }}</h3>
            <h3 class="red">горячее предложение</h3>
            <p class="price">{{ product.price }}<span>руб</span></p>
            <a href="{% url 'basket:add' pk=product.pk %}" class="red-button">
                заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
            </a>
            <div class="description-text">
                {{ product.description}}
            </div>
        </div>
    </div>
</div>
{% endblock %}

mainapp/templates/products.html
{% extends 'base.html' %}
{% load static %}
{% block css%}
<link rel="stylesheet" type="text/css" href="{% static 'mainapp/style.css' %}">
{% endblock %}

{% block content %}

<div class="hero-white">
    <div class="header clearfix">
        {% include "includes/main_menu.html" %}
        <a href="#" class="basket"></a>
    </div>
</div>

<div class="details">
    <div class="links clearfix">
        <ul class="links-menu">
            <li>
                <a href="{% url 'products:category' 0 %}"
                   class="{% if request.resolver_match.kwargs.pk == 0 %}active{% endif%}">ВСЕ
                </a>
            </li>
            {% for link in links_menu %}
            <li>
                <a href="{% url 'products:category' link.pk %}"
                   class="{% if request.resolver_match.kwargs.pk|add:'0' == link.pk %}
                        		active{% endif %}">
                    {{ link.name }}
                </a>
            </li>
            {% endfor%}
        </ul>
    </div>

    <div class="details-products">
        <div class="details-slider">
            <div class="slider-product">
                <img src="{{hot_product.image.url}}">
            </div>
            <div class="slider-control">
                <div class="block">
                    <a href="#"><img src="{% static '/geekshop/img/controll.jpg' %}" alt="">
                        <div class="text"></div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="{% static '/geekshop/img/controll1.jpg' %}" alt="">
                        <div class="text"></div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="{% static '/geekshop/img/controll2.jpg' %}" alt="">
                        <div class="text"></div>
                    </a>
                </div>
            </div>
        </div>

        <div class="description">
            <h3 class="big-bold">{{ hot_product.short_desc }}</h3>
            <h3 class="red">горячее предложение</h3>
            <p class="price">{{ hot_product.price }}<span>руб</span></p>
            <a href="{% url 'mainapp:details' pk=hot_product.pk %}" class="red-button">
                заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
            </a>
            <div class="description-text">
                {{ hot_product.description}}
            </div>
        </div>
    </div>

    <div class="products_list">
        <div class="title clearfix">
            {% if category %}
            <h2>
                Категория: "{{ category.name|title }}"
            </h2>
            {% endif%}
        </div>
        <div class="related-products clearfix">
            <div class="paginator">
                {% if products.has_previous %}
                <a href="{% url 'products:page' category.pk products.previous_page_number %}">
                    <
                </a>
                {% endif %}
                <span class="current">
            страница {{ products.number }} из
            {{ products.paginator.num_pages }}
          </span>
                {% if products.has_next %}
                <a href="{% url 'products:page' category.pk products.next_page_number %}">
                    >
                </a>
                {% endif %}
            </div>
        </div>

        {% for product in products %}
        <div class="block">
            <a href="{% url 'mainapp:details' pk=product.pk %}">
                <img src="/media/{{product.image}}" alt="product">
                <div class="text">
                    <img src="{% static '/geekshop/img/icon-hover.png'%}" alt="hover">
                    <h4>{{ product.name }}</h4>
                    <p>{{ product.short_desc }}</p>
                </div>
            </a>
        </div>
        {% endfor%}
    </div>
</div>

<div class="related">
    <div class="title clearfix">
        <h2>Похожие продукты</h2>
        <a class="explore" href="#">показать все<img src="{% static '/geekshop/img/arrow.png' %}" alt=""></a>
    </div>
    <div class="related-products clearfix">
        {% for product in same_products %}
        <div class="block">
            <a href="{% url 'mainapp:details' pk=product.pk %}"><img src="/media/{{ product.image }}"
                                                                     alt="{{ product.short_desc }}">
                <div class="text">
                    <img src="{% static '/geekshop/img/icon-hover.png' %}" alt="img">
                    <h4>{{ product.name }}</h4>
                    <p>{{ product.short_desc }}</p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
</div>
{% endblock %}