adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.user_create, name='user_create'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),

    path('categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>/', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
]

authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name="login"),
    path("logout/", authapp.logout, name="logout"),

    path("register/", authapp.register, name="register"),
    path("edit/", authapp.edit, name="edit"),
    path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),

]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import index, contact


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', index, name='index'),
    path('contact/', contact, name='contact'),

    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('order/', include('ordersapp.urls', namespace='order')),

    path('', include('social_django.urls', namespace='social'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django import forms
from authapp.models import ShopUser
from authapp.forms import ShopUserEditForm
from mainapp.models import ProductCategory, Product


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'




class ProductCategoryEditForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ProductCategoryEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ProductEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

adminapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy

from adminapp.forms import ShopUserAdminEditForm, ProductEditForm, ProductCategoryEditForm
from authapp.forms import ShopUserRegisterForm
from authapp.models import ShopUser
from mainapp.models import ProductCategory, Product
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django.contrib.auth.decorators import user_passes_test
from django.utils.decorators import method_decorator


class UsersListView(ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'
    context_object_name = 'objects'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UsersListView, self).get_context_data(**kwargs)
        context['title'] = 'админка/пользователи'

        return context

        



@user_passes_test(lambda u: u.is_superuser)
def user_create(request):
    title = 'пользователи/создание'

    if request.method == 'POST':
        user_from = ShopUserRegisterForm(request.POST, request.FILES)
        if user_from.is_valid():
            user_from.save()
            return HttpResponseRedirect(reverse('admin_staff:users'))
    else:
        user_from = ShopUserRegisterForm()

    context = {
        'title': title,
        'user_form': user_from,
    }

    return render(request, 'adminapp/user_update.html', context)




@user_passes_test(lambda u: u.is_superuser)
def user_update(request, pk):
    title = 'пользователи/редактирование'

    edit_user = get_object_or_404(ShopUser, pk=pk)
    if request.method == 'POST':
        edit_form = ShopUserAdminEditForm(request.POST, request.FILES, instance=edit_user)

        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('admin_staff:user_update', args=[edit_user.pk]))
    else:
        edit_form = ShopUserAdminEditForm(instance=edit_user)

    context = {
        'title': title,
        'user_form': edit_form,
    }

    return render(request, 'adminapp/user_update.html', context)


@user_passes_test(lambda u: u.is_superuser)
def user_delete(request, pk):
    title = 'пользователи/удаление'

    user = get_object_or_404(ShopUser, pk=pk)

    if request.method == 'POST':
        user.is_active =False
        user.save()
        return HttpResponseRedirect(reverse('admin_staff:users'))

    context = {
        'title': title,
        'user_to_delete': user,
    }

    return render(request, 'adminapp/user_to_delete.html', context)


@user_passes_test(lambda u: u.is_superuser)
def categories(request):
    title = 'админка/категории'

    categories_list = ProductCategory.objects.all()

    context = {
        'title': title,
        'objects': categories_list,
    }

    return render(request, 'adminapp/categories.html', context)


class ProductCategoryCreateView(CreateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('admin_staff:categories')
    form_class = ProductCategoryEditForm



# @user_passes_test(lambda u: u.is_superuser)
# def category_create(request):
#     pass


class ProductCategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('admin_staff:categories')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'категория/редактирование'

        return context

# @user_passes_test(lambda u: u.is_superuser)
# def category_update(request, pk):
#     pass


class ProductCategoryDeleteView(DeleteView):
    model = ProductCategory
    template_name = 'adminapp/category_delete.html'
    context_object_name = 'product_to_delete'
    success_url = reverse_lazy('admin_staff:categories')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())

# @user_passes_test(lambda u: u.is_superuser)
# def category_delete(request, pk):
#     pass


@user_passes_test(lambda u: u.is_superuser)
def products(request, pk):
    title = 'админка/продукт'

    category = get_object_or_404(ProductCategory, pk=pk)
    products_list = Product.objects.filter(category__pk=pk).order_by('name')

    context = {
        'title': title,
        'category': category,
        'objects': products_list,
    }

    return render(request, 'adminapp/products.html', context)


@user_passes_test(lambda u: u.is_superuser)
def product_create(request, pk):
    title = 'продукт/создание'
    category = get_object_or_404(ProductCategory, pk=pk)

    if request.methid == 'POST':
        product_form = ProductEditForm(request.POST, request.FILES)
        if product_form.is_valid():
            product_form.save()
            return HttpResponseRedirect(reverse('admin_staff:products', args=[pk]))

    else:
        product_form = ProductEditForm(initial={'category': category})

    context ={
        'title': title,
        'update_form': product_form,
        'category': category,
    }

    return render(request, 'adminapp/product_update.html', context)


@user_passes_test(lambda u: u.is_superuser)
def product_read(request, pk):
    title = 'продукт/подробнее'
    product = get_object_or_404(Product, pk=pk)
    context = {
        'title': title,
        'object': product,
    }

    return render(request, 'adminapp/product_read.html', context)


@user_passes_test(lambda u: u.is_superuser)
def product_update(request, pk):
    title = 'продукт/редактирование'

    edit_product = get_object_or_404(Product, pk=pk)

    if request.method == 'POST':
        edit_form = ProductEditForm(request.POST, request.FILES, instance=edit_product)

        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('admin_staff:product_update', args=[edit_product.pk]))

    else:
        edit_form = ProductEditForm(instance=edit_product)

    context = {
        'title': title,
        'update_form': edit_form,
        'category': edit_product.category
    }

    return render(request, 'adminapp/product_update.html', context)


@user_passes_test(lambda u: u.is_superuser)
def product_delete(request, pk):
    title ='продукт/удаление'

    product = get_object_or_404(Product, pk=pk)

    if request.method == 'POST':
        product.is_active = False
        product.save()
        return HttpResponseRedirect(reverse('admin_staff:products', args=[products.category.pk]))

    context = {
        'title':title,
        'product_to_delete':product,
    }

    return render(request, 'adminapp/product_delete.html', context)

adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
        {{ title|title }}
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'adminapp/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href='https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css'>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
            integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css">

    {% block css %}
    {% endblock %}

    <script src='{% static "adminapp/js/sctipt.js" %}'></script>

    {% block js %}
    {% endblock %}
</head>
<body id="body-pd">
<header class="header" id="header">
    <div class="header_toggle"><i class='bx bx-menu' id="header-toggle"></i></div>
    <div class="header_img"><img src="/media/{{ user.avatar|default:'avatar.png' }}" alt=""></div>
</header>
<div class="l-navbar" id="nav-bar">
    <nav class="nav">
        <div>
            <a href="{% url 'index' %}" class="nav_logo">
                <i class='bx bx-layer nav_logo-icon'></i>
                <span class="nav_logo-name">Admin`ka</span>
            </a>
            {% include 'adminapp/inludes/inc_admin_menu.html' %}
        </div>
        <a href="{% url 'auth:logout' %}" class="nav_link"> <i class='bx bx-log-out nav_icon'></i> <span
                class="nav_name">Выход</span> </a>
    </nav>
</div>
<!--Container Main start-->
<div class="height-100 bg-light">
    {% block content %}
    {% endblock %}
</div>
<!--Container Main end-->
</body>
</html>

adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Категории товаров</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Категории
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Наименование</th>
                            <th>Товары</th>
                            <th>Редактировать</th>
                            <th>Удалить</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Наименование</th>
                            <th>Товары</th>
                            <th>Редактировать</th>
                            <th>Удалить</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for category in objects %}
                            <tr {% if not category.is_active %} style="opacity: 0.5;" {% endif %}>
                                <td>{{ category.name }}</td>
                                <td><a href="{% url 'admin_staff:products' category.pk %}">Товары</a></td>
                                <td class="text-center">
                                    <a href="{% url 'admin_staff:category_update' category.pk %}">Edit</a>
                                </td>
                                <td>
                                    <a {% if not category.is_active %} class="invisible" {% endif %} href="{% url 'admin_staff:category_delete' pk=category.pk %}">
                                        <i class="fa fa-times-circle"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'admin_staff:category_create' %}">
                    <button class="btn btn-success">Создать категорию</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}

adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="user_delete">
    Уверены, что хотите удалить {{ product_to_delete.name }}

    ?
    <form action="{% url 'admin_staff:category_delete' product_to_delete.pk %}" method="post">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
        <a href="{% url 'admin_staff:categories' %}">
            Отмена
        </a>
    </button>
</div>
{% endblock %}

adminapp/templates/adminapp/category_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="btn btn-primary">Сохранить</button>
</form>
{% endblock %}

adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="user_delete">
    Уверены, что хотите удалить {{ product_to_delete.name }}

    ?
    <form action="{% url 'admin_staff:product_delete' product_to_delete.pk %}" method="post">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
        <a href="{% url 'admin_staff:products' product_to_delete.category.pk %}">
            Отмена
        </a>
    </button>
</div>
{% endblock %}

adminapp/templates/adminapp/product_read.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="card" style="width: 18rem;">
    <img src="{{ object.image.url }}" class="card-img-top" alt="...">
    <div class="card-body">
        <h5 class="card-title">{{ object.name }}</h5>
        <p class="card-text">{{ object.description }}</p>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">An item</li>
        <li class="list-group-item">A second item</li>
        <li class="list-group-item">A third item</li>
    </ul>
    <div class="card-body">
        <a href="#" class="card-link">Card link</a>
        <a href="#" class="card-link">Another link</a>
    </div>
</div>

{% endblock %}

adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ update_form }}
    <button type="submit" class="btn btn-primary">Сохранить</button>
</form>
{% endblock %}

adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Товары</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Товары категории: <strong>{{ category.name|title }}</strong>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Наименование</th>
                            <th>Количество</th>
                            <th>Стоимость</th>
                            <th>Детали</th>
                            <th>Редактировать</th>
                            <th>Удалить</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Наименование</th>
                            <th>Количество</th>
                            <th>Стоимость</th>
                            <th>Детали</th>
                            <th>Редактировать</th>
                            <th>Удалить</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for product in objects %}
                        <tr {% if not product.is_active %} style="opacity: 0.5;" {% endif %}>
                            <td>{{ product.name }}</td>
                            <td>{{ product.quantity }}</td>
                            <td>{{ product.price }}</td>
                            <td class="text-center">
                                <a href="{% url 'admin_staff:product_read' product.pk %}">Detail</a>
                            </td>
                            <td class="text-center">
                                <a href="{% url 'admin_staff:product_update' product.pk %}">Edit</a>
                            </td>
                            <td>
                                <a {% if not product.is_active %} class="invisible" {% endif %}
                                   href="{% url 'admin_staff:product_delete' pk=product.id %}">
                                    <i class="fa fa-times-circle"></i>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'admin_staff:product_create' category.pk %}">
                    <button class="btn btn-success">Создать товар</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}

adminapp/templates/adminapp/user_to_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="user_delete">
    Уверены, что хотите удалить {{ user_to_delete.username }}
    {% if user_to_delete.first_name %}
    ({{ user_to_delete.first_name|title }}</b>
    {% if user_to_delete.last_name %}
    {{ user_to_delete.last_name|title }}
    {% endif %})
    {% endif %}
    ?
    <form action="{% url 'admin_staff:user_delete' user_to_delete.pk %}" method="post">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
        <a href="{% url 'admin_staff:users' %}">
            Отмена
        </a>
    </button>
</div>
{% endblock %}

adminapp/templates/adminapp/user_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_form }}
    <button type="submit" class="btn btn-primary">Сохранить</button>
</form>
{% endblock %}

adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Пользователи</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Пользователи
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Имя пользователя</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Адрес эл. почты</th>
                            <th>Персонал сайта</th>
                            <th>Активный</th>
                            <th>Вход</th>
                            <th>Удалить</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Имя пользователя</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Адрес эл. почты</th>
                            <th>Персонал сайта</th>
                            <th>Активный</th>
                            <th>Вход</th>
                            <th>Удалить</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for user in object_list %}
                            <tr {% if not user.is_active %} style="opacity: 0.5; text-decoration: line-through;" {% endif %}>
                                <td><a href="{% url 'admin_staff:user_update' user.id %}" style="color: dodgerblue">{{ user.username }}</a></td>
                                <td>{{ user.first_name }}</td>
                                <td>{{ user.last_name }}</td>
                                <td>{{ user.email }}</td>
                                <td class="text-center">
                                    {% if user.is_staff %}
                                        <i class="fa fa-check-circle"></i>
                                        {% else %}
                                        <i class="fa fa-times-circle"></i>
                                    {% endif %}
                                </td>
                                <td class="text-center">
                                    {% if user.is_active %}
                                        <i class="fa fa-check-circle"></i>
                                        {% else %}
                                        <i class="fa fa-times-circle"></i>
                                    {% endif %}
                                </td>
                                <td>{{ user.last_login }}</td>
                                <td>
                                    <a {% if not user.is_active %} class="invisible" {% endif %}
                                       href="{% url 'admin_staff:user_delete' pk=user.id %}">
                                        <i class="fa fa-times-circle"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'adminapp:user_create' %}">
                    <button class="btn btn-success">Создать пользователя</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}