adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.user_create, name='user_create'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),

    path('categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>/', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
]

authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name="login"),
    path("logout/", authapp.logout, name="logout"),

    path("register/", authapp.register, name="register"),
    path("edit/", authapp.edit, name="edit"),
    path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),

]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import index, contact


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', index, name='index'),
    path('contact/', contact, name='contact'),

    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('order/', include('ordersapp.urls', namespace='order')),

    path('', include('social_django.urls', namespace='social'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from .views import products, product


app_name = 'mainapp'

urlpatterns = [
    path('', products, name='products'),
    path('category/<int:pk>/', products, name='category'),
    path('category/<int:pk>/page/<int:page>/', products, name='page'),
    path('product/<int:pk>/', product, name='details'),

]

ordersapp/urls.py
from django.urls import path
import ordersapp.views as ordersapp

app_name = 'ordersapp'


urlpatterns = [
    path('', ordersapp.OrderList.as_view(), name='orders_list'),
    path('forming/complete/<int:pk>/', ordersapp.order_forming_complete, name='order_forming_complete'),
    path('create/', ordersapp.OrderCreate.as_view(), name='order_create'),
    path('read/<int:pk>/', ordersapp.OrderRead.as_view(), name='order_read'),
    path('update/<int:pk>/', ordersapp.OrderUpdate.as_view(), name='order_update'),
    path('delete/<int:pk>/', ordersapp.OrderDelete.as_view(), name='order_delete'),
]

geekshop/views.py
from django.shortcuts import render
from mainapp.models import Product




def index(request):
    title = "GeekShop"

    products = Product.objects.all()[:3]

    context = {
        "title": title,
        "products": products,
    }
    return render(request, 'index.html', context)


def contact(request):
    title = "контакты"

    context = {
        "title": title,

    }
    return render(request, 'contact.html', context)

geekshop/templates/includes/main_menu.html
{% load static %}

<a href="{% url 'index' %}" class="logo"></a>
<ul class="menu">
	<li><a href="{% url 'index' %}" class="active">домой</a></li>
	<li><a href="{% url 'products:products' %}">продукты</a></li>
	<li><a href="{% url 'contact' %}">контакты</a></li>

        {% if user.is_authenticated %}
        <li class="dropdown-toggle"  id="dropdownMenuButton1"
                data-bs-toggle="dropdown" aria-expanded="false">
            <a href="{% url 'auth:edit'%}">
                {{ user.first_name|default:'Пользователь'}}
            </a>
        </li>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
            <li>
                <a class="dropdown-item" href="{% url 'auth:edit'%}">
                    Профиль
                </a>
            </li>
            <li>
                <a class="dropdown-item" href="{% url 'ordersapp:orders_list'%}">
                    Заказы
                </a>
            </li>
            {% if user.is_superuser%}
                <li>
                    <a class="dropdown-item" href="{% url 'admin_staff:users'%}">
                        админка
                    </a>
                </li>
            {% endif%}
        </ul>
	{% endif%}
	<li>
		{% if user.is_authenticated %}
			<a href="{% url 'auth:logout' %}">выйти</a>
		{% else %}
			<a href="{% url 'auth:login' %}">войти</a>
		{% endif%}
	</li>
	{% if basket %}
		<li>
			<a href="{% url 'basket:index' %}" class="basket">
				<span>
					{{ basket.0.total_cost|floatformat:0 }} руб
					({{ basket.0.total_quantity }} шт)
				</span>
			</a>
		</li>
	{% endif %}
</ul>
<a href="#" class="search"></a>